import { createTRPCReact } from '@trpc/react-query';
import type { AppRouter } from '../server/trpc/routers';
import type { Metadata } from 'next';
import './globals.css';
import { TRPCReactProvider } from './_providers';

export const metadata: Metadata = {
  title: 'MetaData test',
  description: 'Generated by create next app',
};

export const trpc = createTRPCReact<AppRouter>();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
