import { createTRPCReact } from '@trpc/react-query';
import type { AppRouter } from '../server/trpc/routers';
import { Providers } from './_providers';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'MetaData test',
  description: 'Generated by create next app',
};

export const trpc = createTRPCReact<AppRouter>();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
